### ISSUE TITLE
PHP 7+ 프로그래밍 댓글 쓰는 곳이 없어서 여기에...

### ISSUE THREAD

**Issue by GalaxyGold** [pronist/php7-basic#2]
PHP 7+ 프로그래밍 강좌를 결제하기 전에 문의가 있어서요. 
그 강좌에서 알려주는 것들이 다 보안이 되있는 소스로 강의하나요.

**Comment by pronist** [comment]
인프런 측으로부터 전달을 받으셨을 지 모르겠지만,
그래도 혹시 몰라 다시 적습니다.

현재 강좌에 나타난 게시판의 기능으로만 본다면, 보안의 측면에서는 충분하다고 볼 수 있습니다. 
하지만, 강좌에 나타나지 않은 기능,
예를 들어 **파일 업로드**, **다운로드**에는 추가적으로 처리 해야 할 보안 요소가 발생합니다.
게시판에 기능이 추가되면 추가 될 수록 처리해야 할 보안도 늘어납니다.

**Comment by GalaxyGold** [comment]
메일 오자마자 읽었습니다. 답변 감사합니다.
